version: '2.1'
services:
  solr:
    image: ${REGISTRY_HOST}${REGISTRY_URI}:${TAG}
    ports:
      - '8983:8983'
    volumes:
      - './solr/conf:/opt/config:delegated'
    env_file:
      - .env
    build:
      context: .
