version: '2.1'
services:
  solr:
    image: ${REGISTRY_HOST}${REGISTRY_URI}:${SOLR_TAG:-latest}
    ports:
      - '8983:8983'
    ulimits:
      nofile:
          soft: 65000
          hard: 65000
    volumes:
      - '/opt/config'
      - solr:/opt/solr/server/solr/mycores
    env_file:
      - .env
    build:
      context: .
    command: bash -c 'precreate-core ${SOLR_CORE} /opt/config; precreate-core ${SOLR_TEST_CORE} /opt/config; exec solr -f'

volumes:
  solr: