version: '2.1'
services:
  solr:
    image: yalelibraryit/dc-solr:${COMMIT}
    ports:
      - '8983:8983'
    volumes:
      - './solr/conf:/opt/config:delegated'
    env_file:
      - .env
    build:
      context: .
